upstreams:
  - name: "mockbinUpstream"
    ensure: "present"
    targets:
      - target: "server1.mockbin:3001"
        attributes:
          weight: 50
      - target: "server2.mockbin:3001"
        attributes:
          weight: 50
    attributes:
      slots: 10
      healthchecks:
        active:
          unhealthy:
            http_statuses:
              - 404
            tcp_failures: 1
            timeouts: 1
            http_failures: 1
            interval: 1
          http_path: /health
          healthy:
            http_statuses:
              - 200
            interval: 1
            successes: 1
          timeout: 1
          concurrency: 1
        passive:
          unhealthy:
            http_failures: 1
            http_statuses:
              - 404
            tcp_failures: 1
            timeouts: 1
          healthy:
            successes: 1
            http_statuses:
              - 200
